version: "3.3"
services:
  vaccine_helper_db:
    container_name: vaccine_h_db
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_DB: vaccine_helper_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5000:5432"
    volumes:
      - vaccine_volume:/var/lib/postgresql/
volumes:
  vaccine_volume: